feat(bin): Trigger expiry for missing certs

diff --git a/bin/certhub-cert-expiry b/bin/certhub-cert-expiry
--- a/bin/certhub-cert-expiry
+++ b/bin/certhub-cert-expiry
@@ -26,13 +26,16 @@ certbot_cert_expiry() {
     THRESHOLD="${2}"
     shift 2
 
-    if ${OPENSSL} x509 -in "${CERTFILE}" -noout >/dev/null; then
+    if [ ! -f "${CERTFILE}" ]; then
+        "${@}"
+        RESULT=0
+    elif ${OPENSSL} x509 -in "${CERTFILE}" -noout >/dev/null; then
         if ! ${OPENSSL} x509 -in "${CERTFILE}" -checkend "${THRESHOLD}" -noout >/dev/null; then
             "${@}"
         fi
         RESULT=0
     else
-        ${ECHO} "Certificate file missing or invalid" >&2
+        ${ECHO} "Certificate file invalid" >&2
         RESULT=1
     fi
 
